In [1]:
import numpy as np


In [2]:
a = np.array([1,2, 3, 4, 5, 6])
a
a[2] = 10
a[2]

10

In [4]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [15]:
np.linspace(0, 100, 11) # creates array with evenly spaced elements in a given range


array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

# Multi-dimensional array

In [21]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [31]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

In [32]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
n[:, 2] = [0, 1, 2]
n

array([[1, 2, 0],
       [4, 5, 1],
       [7, 8, 2]])

In [33]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Randomly generated array

In [46]:
np.random.seed(3)
np.random.rand(5, 2)

array([[0.5507979 , 0.70814782],
       [0.29090474, 0.51082761],
       [0.89294695, 0.89629309],
       [0.12558531, 0.20724288],
       [0.0514672 , 0.44080984]])

## Element-wise operations

In [47]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [49]:
b = (10 + (a*2))
b

array([10, 12, 14, 16, 18])

In [50]:
a >= 2


array([False, False,  True,  True,  True])

In [51]:
a > b

array([False, False, False, False, False])

# Summarize

In [52]:
a

array([0, 1, 2, 3, 4])

In [54]:
a.std() # S.D

1.4142135623730951

In [55]:
a.min()

0

In [56]:
a.max()

4

In [57]:
a.sum()

10